---
output: html_document
---


```{r, echo=FALSE, message=FALSE}
### Exercise 1 ###

library(jsonlite)
library(dplyr)

# Store a variable "movie"

# Write a function that allows you to specify a movie, then does the following:
GetReview <- function(movie) {
  movie.no.spaces <-  gsub(" ", "+", movie)
    base.url <- 'https://api.nytimes.com/svc/movies/v2/reviews/search.json?'
    api.key <- '&api-key=0089fb447baf4fcfaa42c3b931aa4e09'
    request <- paste0(base.url, 'query=', movie.no.spaces, api.key)
    results <- fromJSON(request)
    flattened <- flatten(results$results)
    first.review <- flattened[1,]
    headline <- first.review$headline
    summary <- first.review$summary_short
    link <- first.review$link.url
    info <- list(headline=headline, summary=summary, link=link)
    return(info)
  }
  # Replace all of the spaces in your movie title with plus signs (+)
  
  
  # Construct a search query using YOUR api key
  # The base URL is https://api.nytimes.com/svc/movies/v2/reviews/search.json?
  # See the interactive console for more detail:https://developer.nytimes.com/movie_reviews_v2.json#/Console/GET/reviews/search.json
  
  
  
  # Request data using your search query
  
  
  # Flatten the data stored in the `$results` key of the data returned to you
  
  
  # From the most recent review, store the headline, short summary, and link to full article each in their own variables
  
  
  # Return an list of the three pieces of information from above
  

# Create a variable called `movie.info` by passing your movie to your GetReview function
movie.info <- GetReview('If I Stay')
```
``` {r, echo = FALSE}
movie <- 'If I Stay'
movie.info <- GetReview('If I Stay')
```
# `r movie`
## `r movie.info$headline`
>`r movie.info$summary`

Link to the the full movie review: [This Link](`r movie.info$link`)


